### ISSUE TITLE
jq: command not found

### ISSUE THREAD

**Issue by leosussan** [virtualstaticvoid/asdf-docker-compose#1]
```bash
> asdf list all docker-compose
/Users/***/.asdf/plugins/docker-compose/bin/list-all: line 24: jq: command not found
```

**Comment by virtualstaticvoid** [comment]
Hi @leosussan

You will need to have jq installed.

You can install jq with snap on Linux or brew on Mac. 

See https://stedolan.github.io/jq/ for more details.

**Comment by leosussan** [comment]
in your code, there's a line that's presumably [supposed to acquire a portable version of `jq`](https://github.com/virtualstaticvoid/asdf-docker-compose/blob/master/bin/list-all#L18) if not available, but that doesn't seem to be doing its' job. This is the reason I submitted this issue.

Zooming out a bit - `asdf` plugin acquisition really should not require additional dependencies (this is the only one that gives such an error).

May be worth looking at other third-party plugins to see how they acquire a list w/o additional dependencies (e.g. https://github.com/crflynn/asdf-poetry/blob/master/bin/list-all)

**Comment by leosussan** [comment]
@virtualstaticvoid ^^ edited my last comment a bit.

**Comment by virtualstaticvoid** [comment]
Ah, cool.
